platform :ios, '7.0'

pod 'Parse', '1.7.4'
pod 'ParseUI'
pod 'ParseFacebookUtils', '1.7.4'
pod 'Facebook-iOS-SDK'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'CRToast', '~> 0.0.7'
pod 'Google/Analytics'
pod 'PMEDatePicker'
pod 'UIImageViewModeScaleAspect'