platform :ios, '8.0'

pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtils'
pod 'Facebook-iOS-SDK'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'CRToast', '~> 0.0.7'
pod 'Google/Analytics'
pod 'PMEDatePicker'
pod 'UIImageViewModeScaleAspect'
pod 'CrittercismSDK'
pod 'MPSkewed'
pod 'Shimmer'
pod 'NYTPhotoViewer'